### ISSUE TITLE
Remove `xblock-utils` dependency

### ISSUE THREAD

**Issue by Agrendalath** [open-craft/xblock-poll#114]
Parent ticket: https://github.com/openedx/axim-engineering/issues/915

This repository is using the [xblock-utils](https://github.com/openedx/xblock-utils/) package, which has been deprecated and migrated to within the xblock package.

In this ticket, we will:
```[tasklist]
### Tasks
- [ ] Make sure the repository is using xblock [version 1.8.1](https://github.com/openedx/XBlock/releases/tag/xblock-1.8.0) or above. Upgrade the version if required, preferably via the `make upgrade` command.
- [ ] Remove the `xblock-utils` package.
- [ ] Find and replace all the `xblockutils.*` imports with `xblock.utils.*`. Provide the fallback mentioned below.
- [ ] Make sure all the test cases are passing.
- [ ] Test the XBlock.
```

Fallback for imports:
```python
try:
    from xblock.utils.resources import ResourceLoader
    from xblock.utils.settings import ThemableXBlockMixin, XBlockWithSettingsMixin
except ModuleNotFoundError:  # For backward compatibility with releases older than Quince.
    from xblockutils.resources import ResourceLoader
    from xblockutils.settings import ThemableXBlockMixin, XBlockWithSettingsMixin
```

**Comment by kdmccormick** [comment]
Additional tasks discovered in https://github.com/open-craft/xblock-poll/pull/127, which I had to abandon over time constraints:

- [ ] Delete integration tests
- [ ] Remove Makefile entries, etc. regarding integration tests
- [ ] Remove bok-choy, selenium, and (maybe?) xblock-sdk from dev requirements
- [ ] Add `XBlock[django]` as a base requirement
- [ ] Recompile requirement .txt files

**Comment by kdmccormick** [comment]
@Agrendalath I noticed that 1.14.0 will fix the log warnings--thanks! When the upgrade lands in edx-platform master, assuming it's not risky, would you mind backporting it to Redwood? I think this would be a nice touch to make the release easier for operators to work with.
